language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - pip install -r tests/requirements.txt
  - pip install $DJANGO
  - pip install coveralls
  - pip install -e .

script:
  - invoke test

env:
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"

after_success: coveralls
