language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - make install
  - pip install $DJANGO
script:
  - "make travis"
env:
  - DJANGO="Django==1.5.1"
  - DJANGO=https://github.com/django/django/tarball/master
