language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - make install
  - pip install . coveralls https://github.com/django/django/archive/${DJANGO}.zip#egg=django

script:
  - make travis

env:
  - DJANGO=1.5.1
  - DJANGO=master

after_success: coveralls
